name: True-Buddy Chatbot CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    name: Code standard analysing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install pylint
          sudo apt-get update && sudo apt-get install -y bc

      - name: Code linting with pylint on Streamlit app
        run: |
          SCORE=$(pylint app.py --exit-zero | grep -oP 'rated at \K[0-9]+\.[0-9]+')
          echo "Pylint score: $SCORE"
          if (( $(echo "$SCORE < 8" | bc -l) )); then
            echo "Pylint score is less than 8. Failing the workflow."
            exit 1
          fi